const MESSAGES = {
    CLOSE: [
        "Victoire de justesse, t'as eu un coup de bol monstrueux.", "Même mon grand-père joue mieux avec une cataracte.",
        "C'est serré, mais vous êtes tous les deux des nuls.", "On s'est fait chier à regarder ça.",
        "Plus proche, c'était le ridicule. Félicitations pour rien.", "Une purge de 30 minutes. Changez de passe-temps.",
        "Ça s'est joué à la chance, votre talent est inexistant.", "C'est passé, mais c'était pathétique.",
        "Un match de niveau maternelle. Vous avez honte ?", "Le suspense, c'est pour les faibles qui savent pas jouer.",
        "Bravo, t'as gagné contre un plot. T'es fier ?", "C'était pas du sport, c'était une insulte au ballon.",
        "Vous avez galéré pour ça ? Quelle tristesse.", "Le niveau est abyssal, changez de vie.",
        "C'est passé, mais c'était moche à voir.", "Regarder ce match m'a filé un cancer des yeux.",
        "Vous êtes nuls, mais le destin a tranché.", "La victoire est dégueulasse.",
        "T'as gagné d'un rien, arrête de frimer, t'es une quiche.", "Un match indigne d'un tournoi.",
        "Vous êtes tellement mauvais que c'en est presque comique.", "Le prochain qui joue comme ça, je le vire.",
        "C'était serré ? Non, c'était juste médiocre.", "Quelle perte de temps monumentale.",
        "Le fair-play, c'est pour les perdants comme vous.", "Arrêtez le massacre et rentrez chez vous.",
        "Si c'est ça votre niveau, vous êtes pas arrivés.", "Un match à oublier, comme votre existence.",
        "T'as gagné par accident, c'est ça ?", "Une performance de bras cassés.",
        "La chance a choisi le moins mauvais. Bravo, t'es pathétique.", "Quelle purge !",
        "C'était tendu comme un string sale.", "J'ai vu des autistes jouer mieux que ça.",
        "Vous êtes des handicapés du jeu.", "Le niveau est tellement bas qu'il creuse.",
        "Bravo, vous avez réussi à finir le match sans vous évanouir.", "Pathétique.",
        "C'est passé, mais n'espère pas aller plus loin, bouffon.", "Zéro talent, 100% de chance.",
        "Vous me donnez envie de vomir.", "Un match pour les ratés.",
        "C'est ça, le niveau ? Je pleure pour vous.", "Une vraie blague ce duel.",
        "Vous avez essayé de jouer ou quoi ?", "T'as gagné ? T'es juste le roi des cons.",
        "Quelle médiocrité ambiante !", "J'ai perdu des neurones en regardant ça.",
        "Rien à sauver dans cette rencontre.", "Vous êtes des nuls, assumez-le.",
        "C'était moche, lent et débile.", "Le vainqueur est juste le moins nul.",
        "Vous devriez être bannis du terrain.", "Félicitations, vous êtes des losers.",
        "Quelle honte, ce match.", "C'est ça votre 'intensité' ?", "Rentrez à la niche.",
        "Zéro technique, zéro tactique, juste des bras cassés.", "Une purge totale.",
        "Vous avez prouvé votre nullité en 90 minutes.", "J'ai honte pour vous.",
        "T'as gagné ? T'es juste un gros chatteux.", "Changez de sport, sérieusement.",
        "Plus jamais ça, par pitié.", "Une insulte au tournoi.", "Vous êtes des clowns.",
        "J'ai vomi 3 fois en voyant votre niveau.", "On s'emmerde, mais qu'est-ce qu'on s'emmerde, putain.",
        "Même mon chien joue mieux quand il a la chiasse.", "Une purge monumentale, je veux mes yeux neufs.",
        "Vous êtes des tanches, c'est pas possible d'être aussi nuls.", "Zéro talent, 100% de consanguinité sur le terrain.",
        "Le match le plus inutile de l'histoire du sport.", "Je préfère me taper le pied avec un marteau plutôt que vous revoir.",
        "Vous jouez avec les pieds ou avec vos sphincters ?", "C'est pas du sport, c'est une insulte à mes ancêtres."
    ],
    MEDIUM: [
        "T'as gagné, mais t'es toujours une merde.", "Ils t'ont laissé gagner par pitié.",
        "C'est une victoire ou t'as juste eu de la chance ?", "Ta technique est aussi dégueulasse que ton look.",
        "Tu te prends pour un champion ? Redescends, t'es juste nul.", "Même un chien mort jouerait mieux.",
        "Tu as dominé, mais t'es quand même un tocard.", "Propre ? Non, c'était juste eux qui étaient encore plus nazes.",
        "Tu as gagné, et pourtant tout le monde te déteste.", "Ne prends pas la grosse tête, t'es une quiche.",
        "Une victoire de raté pour un raté.", "T'as gagné par KO technique, c'est ça ton excuse ?",
        "Il va falloir changer de sport, t'as aucune dignité.", "La leçon du jour : t'es toujours aussi mauvais.",
        "Une victoire avec la manière ? Non, c'était juste de la chance.", "Tu es pathétique à regarder.",
        "Ils sont sortis de là en lambeaux, tout comme ta réputation.", "Trop facile ? T'as juste eu un adversaire en carton.",
        "Tu es une insulte au jeu.", "Bravo, tu sais compter les points, c'est ton seul talent.",
        "Une victoire de patron... de bac à sable.", "T'es tellement mauvais que même en gagnant t'as l'air nul.",
        "Va te cacher avant que quelqu'un se rende compte de ta nullité.", "Quelle honte ce match.",
        "T'as gagné ? Super, va te faire voir.", "Tu joues comme un pied-de-biche.",
        "Une démonstration de médiocrité, voilà ce que c'était.", "Même ton ombre se moque de toi.",
        "La hiérarchie des nuls est respectée.", "T'es nul, assume, c'est plus facile.",
        "T'as gagné ? T'es quand même une merde.", "Le score ne cache pas ta nullité.",
        "J'ai vu des mollusques avec plus d'énergie que toi.", "T'es une purge ambulante.",
        "Tu es la honte de ce tournoi.", "Ne reviens plus jamais avec un jeu pareil.",
        "Tu as gagné, mais t'as perdu tout respect.", "Va apprendre à jouer, petit sac à merde.",
        "Ton seul talent, c'est d'être insignifiant.", "Tu es un échec vivant.",
        "T'as gagné ? Le monde est cruel.", "Ton jeu est une insulte à l'humanité.",
        "Une victoire de merde pour un joueur de merde.", "Quelle tristesse de te voir jouer.",
        "Tu es le roi des tocards.", "Même en gagnant, t'es pathétique.",
        "T'as gagné, mais t'es quand même une énorme merde.", "T'es tellement mauvais que ta victoire me donne la nausée.",
        "Félicitations, t'es le roi des connards dans une mare de purin.", "Regarder ça, c'est comme lécher un trottoir sale.",
        "T'as gagné ? C'est juste parce que l'autre est encore plus inutile que toi.", "T'as pas de talent, juste une chance de cocu.",
        "Tu m'as fait perdre 30 minutes de ma vie, je te déteste.", "T'es une blague vivante, et pas la drôle.",
        "Va te faire voir avec ta victoire en carton, espèce de tocard.", "La honte, t'as gagné et t'es toujours minable.",
        "J'ai vu des huîtres avec plus d'instinct que toi, sale abruti."
    ],
    DESTRUCTION: [
        "Grosse branlée, t'as détruit leur dignité, sale psychopathe.", "Couilles en acier trempé, ils sont en sang, tu es un monstre.",
        "C'est pas un match, c'est un viol en réunion.", "Retourne dans ton bac à sable, champion de la médiocrité.",
        "Ils sont en morceaux, tu es une ordure, j'adore.", "C'est légal de jouer comme ça ? Tu es un criminel.",
        "T'as tué leur carrière, leur famille et leur honneur.", "Une boucherie, c'est tout ce que tu sais faire.",
        "Le score est une insulte à leur existence.", "Tu es une machine à détruire les rêves.",
        "C'est de la maltraitance pure, tu devrais être en taule.", "Ils ont besoin d'une thérapie, tu es le bourreau.",
        "Tu es une ordure, une machine à humilier.", "Leur dignité est restée sur le terrain, marche dessus.",
        "L'écart est indécent, tu es une bête immonde.", "Tu as détruit leur âme, c'est magnifique.",
        "C'est une exécution sommaire en public.", "Tu es un démon sur le terrain.",
        "Le tableau d'affichage pleure, tout comme eux.", "Tu es une tronçonneuse humaine.",
        "Tu les as renvoyés à la maternelle, espèce de bâtard.", "La violence de ton score est illégale.",
        "Tu es un cancer pour ce sport, continue comme ça.", "Leur coach a sûrement sauté par la fenêtre.",
        "Un carnage à la Duke Nukem, tu es un dieu de la mort.", "Ils ont le score, mais ils ont plus de fierté.",
        "Tu es une humiliation en haute définition.", "Pas de survivants, tu es une machine.",
        "C'est sale, c'est très sale, j'adore ton manque de respect.", "Tu es une fessée géante à toi tout seul.",
        "Ils ont perdu le sens de la vie, merci à toi.", "Tu es une machine à broyer les losers.",
        "C'est pas du sport, c'est une tuerie de masse.", "Tu les as mis en pièces, espèce de psychopathe.",
        "Tu es une honte pour le fair-play, ça te va si bien.", "Un massacre tactique, tu es un génie du mal.",
        "Ils sont en PLS, continue de les piétiner.", "Tu es le roi des ordures.",
        "Une démolition en règle, tu es une ordure.", "Tu es une machine à broyer les espoirs.",
        "C'est ça, la vraie force, écraser les faibles.", "Tu es une machine à éteindre les lumières.",
        "Tu as éteint leurs espoirs, tu es une ordure finie.", "C'est une correction magistrale, espèce de monstre.",
        "Tu es la honte, puissance 1000, j'adore.", "Tu es un massacre ambulant.",
        "Tu as éteint la lumière, ils ne reverront jamais le jour.", "Tu es une correction vivante.",
        "C'est l'humiliation suprême, tu es un maître.", "Tu es une raclée sans merci.",
        "Tu es une démonstration de pure cruauté.", "C'est la fin pour eux, grâce à toi.",
        "Tu es une victoire de brute, une vraie ordure.", "C'est l'humiliation absolue.",
        "Tu es une exécution sommaire, continue de les tuer.", "Tu es un cauchemar incarné.",
        "Tu es une boucherie, tout simplement, espèce de cinglé.",
        "C'est même plus une défaite, c'est un enterrement, espèce de déchet.", "T'as défoncé leur dignité, ils vont se suicider, bravo.",
        "Tu les as humiliés comme des rats, continue, c'est bon.", "C'est une exécution en règle, j'en ai une demi-molle.",
        "T'es un pur psychopathe du score, c'est ignoble, j'adore.", "Ils sont à genoux, crache-leur dessus pendant que tu y es.",
        "T'as transformé le terrain en fosse commune, sale monstre.", "La boucherie est totale, ils ne s'en relèveront jamais.",
        "Tu es une abomination, une insulte au fair-play, continue comme ça.", "Leurs familles doivent pleurer, t'es un génie du mal.",
        "T'as tué tout le monde, tu devrais être banni de cette planète, espèce de brute.", "Quelle putain de démonstration de haine, magnifique."
    ],
    CHAMPION: [
        "Tu es le roi des décombres. T'as tout piétiné, tout détruit. T'es le prédateur alpha de cette fosse à purin.",
        "Champion ? Tu es un putain de monstre de métal. T'as broyé les faibles, comme il se doit.",
        "On applaudit pas, on se prosterne devant la machine à humilier. T'es le roi des bouchers, sale bâtard.",
        "La gloire est à toi, les cadavres de tes adversaires sont ton paillasson. C'est ça, la vraie force.",
        "T'es le patron. Le seul, l'unique, le prédateur dans cette mare de médiocrité. Continue de les dévorer.",
        "Victoire totale. T'as laissé rien d'autre que de la poussière et des larmes derrière toi. T'es une légende.",
        "Champion de la boucherie. T'as gagné le droit de régner sur les cendres de tes victimes.",
        "T'es l'apocalypse incarnée. T'as soulevé la coupe avec le sang de tes victimes. T'es une machine.",
        "Regarde-les pleurer. C'est ça le son de ta réussite : le gémissement des faibles sous tes bottes.",
        "T'es pas un champion, t'es un génocide ambulant sur le terrain. Félicitations, monstre.",
        "Ton niveau est indécent, illégal, presque criminel. T'es une abomination de la nature.",
        "Tu as transformé ce tournoi en un cimetière de rêves. T'es l'architecte de leur échec.",
        "T'as broyé leur honneur, t'as mangé leur ego. T'es un prédateur au sommet de la chaîne alimentaire.",
        "Si la victoire avait un visage, ce serait celui d'un tueur comme toi. Glacé, impitoyable.",
        "T'es pas là pour jouer, t'es là pour effacer leur existence. Mission accomplie, assassin.",
        "La coupe est lourde ? Normal, elle est remplie du poids de leurs humiliations.",
        "Tu es la tempête, ils sont juste le sable qui se fait balayer. Rien de plus, rien de moins.",
        "Regarde tes mains, elles sont couvertes de la gloire de tes massacres. T'es une putain d'arme de guerre.",
        "Ils n'étaient pas tes adversaires, c'étaient tes cibles. T'as fait un carton plein.",
        "Le sommet est réservé aux prédateurs. Et toi, tu viens de verrouiller la porte derrière toi.",
        "Tu ne gagnes pas, tu exécutes. T'es le bourreau officiel de ce tournoi.",
        "Ils sont en morceaux, tu es en métal. C'est ça, la réalité du plus fort.",
        "Bravo, tu viens de prouver que t'es le seul homme dans cette cour de récréation.",
        "T'as laissé des cicatrices indélébiles sur leur esprit. T'es une machine à traumatiser.",
        "Chaque muscle, chaque goutte de sueur, chaque seconde a été une démonstration de domination pure.",
        "Le trône t'appartient, et il est fait de leurs défaites. Installe-toi bien, roi des bouchers.",
        "T'as éteint les lumières. Ils ne reverront jamais le jour après ce que tu leur as fait.",
        "Tu es une insulte à leur médiocrité. T'es trop grand, trop fort, trop violent.",
        "T'es pas humain. T'es une machine de guerre calibrée pour l'humiliation.",
        "Ils ont essayé, ils ont échoué, ils ont péri. Toi, tu as régné.",
        "C'est ça, la loi du plus fort ? Non, c'est la loi de TOI. Tu es la loi.",
        "T'as laissé le terrain en ruines. T'es un cataclysme à toi tout seul.",
        "Regarde la peur dans leurs yeux quand ils croisent ton regard. C'est ça, ta vraie récompense.",
        "T'as pas gagné, tu as conquis. Comme un putain de conquérant barbare.",
        "T'es le pic de l'évolution, le reste c'est juste de la chair à canon.",
        "Ils sont pathétiques, tu es légendaire. Le fossé est immense, comme ta domination.",
        "Tu es une démonstration de force brute et de cruauté tactique. J'adore.",
        "La victoire ne te suffit pas, tu veux leur destruction totale. Et tu l'as eue.",
        "Tu es le roi des lions dans une fosse à rats. Quelle boucherie !",
        "Ils vont faire des cauchemars de toi pendant dix ans. T'es un traumatisme vivant.",
        "Tu n'es pas au-dessus du lot, tu es dans une autre dimension.",
        "T'as brisé leurs espoirs comme du verre. T'es une force de la nature.",
        "T'as gagné ? Non, t'as purgé la compétition de ses erreurs.",
        "Bravo, machine. Maintenant, va trouver des adversaires qui méritent ton temps.",
        "Ils sont tombés comme des dominos devant ta puissance implacable.",
        "Tu es une correction vivante à tout ce qu'ils croyaient savoir.",
        "La coupe est à toi, mais c'est surtout le silence après ta victoire qui est délicieux.",
        "T'as transformé leur espoir en désespoir pur en une fraction de seconde.",
        "T'es une tronçonneuse dans un champ de fleurs. T'as tout fauché.",
        "La force ne s'explique pas, elle s'impose. Et tu t'es imposé violemment.",
        "Tu es la définition même du prédateur alpha. Domination totale.",
        "Tu as gagné parce que tu es un monstre. Et les monstres gagnent toujours.",
        "T'as montré aucune pitié, et c'est pour ça que t'es le meilleur.",
        "T'es une machine à broyer les ego. Rien ne résiste à ton passage.",
        "Leurs carrières sont finies. Tu viens de leur donner le coup de grâce.",
        "T'es une anomalie, une force qui ne devrait pas exister. Continue.",
        "Tu es le chef d'orchestre du chaos. Et aujourd'hui, tu as joué une symphonie de destruction.",
        "La victoire est ton droit de naissance. T'es né pour dominer ces faibles.",
        "Tu as érigé un monument à ta propre gloire sur leurs dépouilles.",
        "T'as pas besoin de chance, t'as besoin de puissance. Et t'en as à revendre.",
        "T'es un Titan. Ils ne sont que des fourmis sous tes pieds.",
        "Tu as prouvé que la faiblesse n'a pas sa place ici. T'es la purge.",
        "T'es le seul à avoir compris que le jeu se joue avec le sang.",
        "Félicitations, tu viens de gagner le droit d'être craint par tous.",
        "T'es la tempête qui dévaste tout. Aucun abri n'est assez solide pour eux.",
        "Tu es le prédateur ultime. Ils ne sont que de la nourriture pour ta légende.",
        "Bravo, champion. T'as prouvé que t'es une machine sans pitié.",
        "Ton nom est désormais synonyme de douleur pour tes adversaires.",
        "T'as tout arraché. Ils n'ont rien pu faire face à ta rage.",
        "Tu es un chef-d'œuvre de brutalité. Le tournoi n'a jamais été aussi bien dominé.",
        "T'es pas un joueur, t'es un fléau. Un fléau qui gagne tout.",
        "T'as gagné parce que t'es le plus dangereux. Et ça, ça ne s'apprend pas.",
        "Leurs pleurs sont la musique qui accompagne ton couronnement.",
        "Tu as transformé le terrain en ton propre terrain de chasse.",
        "T'es une force brute incontrôlable. Une machine de guerre absolue.",
        "Tu es le seul survivant dans un monde de perdants. T'es le roi.",
        "La puissance, c'est ce que tu respires. Et tu l'as imposée à tous.",
        "T'as tout détruit sur ton passage. Tu es une légende de la violence.",
        "Bravo, tu es la peur incarnée. Personne ne veut te revoir.",
        "T'as gagné, mais t'as surtout démontré que t'étais intouchable.",
        "T'es une machine à broyer les rêves. Et t'en as broyé pas mal aujourd'hui.",
        "La victoire te va comme un gant, un gant trempé dans le sang.",
        "Tu es le cauchemar de tous les coachs. Impossible à arrêter.",
        "Ils n'avaient aucune chance face à ta volonté destructrice.",
        "T'es une bête, une machine, un monstre. T'es tout ce qu'ils ne sont pas.",
        "Tu as laissé ta marque dans l'histoire, et elle est faite de ruines.",
        "Champion. Un mot trop petit pour décrire ton carnage.",
        "La compétition était une blague, tu es la réalité brutale.",
        "Tu es le bourreau, ils sont la victime. C'est simple, c'est efficace.",
        "Tu ne joues pas, tu domines. Une différence qui change tout.",
        "Bravo, tu es le roi du désert que tu as créé.",
        "T'es l'apogée de la force. Personne ne peut t'atteindre.",
        "Tu as gagné avec une autorité terrifiante. C'est ça, la grandeur.",
        "T'as broyé les os de leur ambition. T'es une machine implacable.",
        "Ils sont insignifiants face à la montagne que tu es devenu.",
        "Félicitations, machine. Tu as accompli ta mission de destruction.",
        "T'as gagné et tu as humilié. Le combo parfait du prédateur.",
        "Tu es le sommet. Tout le monde en bas n'est que de la poussière.",
        "T'as tout prouvé. Tu es le seul, le vrai, le destructeur."
    ]
};

export function getTrashTalk(scoreA: number, scoreB: number): string {
    const delta = Math.abs(scoreA - scoreB);
    let pool;
    if (delta <= 1) pool = MESSAGES.CLOSE;
    else if (delta <= 3) pool = MESSAGES.MEDIUM;
    else pool = MESSAGES.DESTRUCTION;
    return pool[Math.floor(Math.random() * pool.length)];
}
export function getChampionTrashTalk(): string {
    const pool = MESSAGES.CHAMPION;
    return pool[Math.floor(Math.random() * pool.length)];
}